---
abstract: 'Install the Tree::Manager modules.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Tree-Manager
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Random::Tree::Manager: 0.01
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Task-Tree-Manager/issues
  homepage: https://github.com/michal-josef-spacek/Task-Tree-Manager
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Task-Tree-Manager
version: '0.01'
